// Supabase client setup
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
// Use anon key only - service key should never be exposed on frontend
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.warn('⚠️ Supabase credentials not found. Using localStorage fallback.');
}

export const supabase = SUPABASE_URL && SUPABASE_KEY
  ? createClient(SUPABASE_URL, SUPABASE_KEY)
  : null;

// Database table types - matches waitlist table
export interface WaitlistEntry {
  id?: string;
  email: string;
  tier_name?: string;
  tier_number?: number;
  signup_position?: number;
  referral_code?: string;        // Auto-generated by database trigger (BEAR + 4 chars)
  referred_by?: string;          // Referral code of who referred them
  synced_at?: string;
  linked_referrer_code?: string; // For retroactive linking
  linked_at?: string;
  link_verified?: boolean;
  solana_wallet_address?: string; // Wallet for airdrops
  thirdweb_user_id?: string;      // Auth status from thirdweb
  verified?: boolean;
}

// Airdrop allocation entry - for leaderboard
export interface AirdropAllocation {
  id?: string;
  email: string;
  referral_code: string;
  tier_number: number;
  tier_name: string;
  base_amount: number;
  referral_amount: number;
  action_amount: number;
  bonus_multiplier: number;
  referral_count: number;
  referred_by_code?: string;
  wallet_address?: string;
}

// Legacy type alias for backwards compatibility
export type WaitlistSyncEntry = WaitlistEntry;

export interface TierAvailability {
  tier_number: number;
  max_spots: number;
  claimed_spots: number;
  available_spots: number;
}
