import type { Metadata } from "next";
import Link from "next/link";
import { PayClient } from "./pay-client";
import { ANDROID_WAITLIST_LABEL, IOS_TESTFLIGHT_URL } from "../../lib/downloadLinks";
import { buildBearoSocialMetadata } from "@/lib/social-metadata";

/**
 * Payment request landing page.
 *
 * Consumes the request links generated by the mobile apps
 * (RequestPaymentScreen): /pay?to=U&amount=X&token=Y&network=Z&note=N
 * where `token` is a Token rawValue code (e.g. "USDT0", never the display
 * glyph) and every value is percent-encoded by the sender. All params are
 * optional; the page degrades to a generic download CTA.
 */

interface PaySearchParams {
  to?: string;
  amount?: string;
  token?: string;
  network?: string;
  note?: string;
}

interface PayPageProps {
  searchParams: Promise<PaySearchParams>;
}

// -- Param sanitizers (never trust inbound query values) ---------------------

function sanitizeUsername(value?: string): string | null {
  const cleaned = value?.replace(/[^a-zA-Z0-9_.-]/g, "").slice(0, 30) ?? "";
  return cleaned.length > 0 ? cleaned : null;
}

function sanitizeAmount(value?: string): string | null {
  if (!value || !/^\d{1,10}(\.\d{1,2})?$/.test(value)) return null;
  const parsed = Number.parseFloat(value);
  if (!Number.isFinite(parsed) || parsed <= 0) return null;
  return parsed.toFixed(2);
}

function sanitizeToken(value?: string): string {
  const cleaned = value?.replace(/[^a-zA-Z0-9]/g, "").toUpperCase().slice(0, 10) ?? "";
  return cleaned.length > 0 ? cleaned : "USDC";
}

/** Display names for known network ids (mirrors the app's network picker). */
const NETWORK_NAMES: Record<string, string> = {
  arbitrum: "Arbitrum",
  avalanche: "Avalanche",
  base: "Base",
  berachain: "Berachain",
  bnb: "BNB Chain",
  ethereum: "Ethereum",
  hyperevm: "HyperEVM",
  ink: "Ink",
  mantle: "Mantle",
  near: "Near",
  optimism: "Optimism",
  polygon: "Polygon",
  ronin: "Ronin",
  sei: "Sei",
  solana: "Solana",
  ton: "TON",
  tron: "Tron",
  unichain: "Unichain",
  zksync: "zkSync",
};

function sanitizeNetwork(value?: string): { id: string; name: string } {
  const id = value?.replace(/[^a-z0-9]/gi, "").toLowerCase().slice(0, 20) ?? "";
  if (id.length === 0) return { id: "base", name: NETWORK_NAMES.base };
  return {
    id,
    name: NETWORK_NAMES[id] ?? id.charAt(0).toUpperCase() + id.slice(1),
  };
}

/** Collapse whitespace, trim, cap at the shared 140-char note limit. */
function sanitizeNote(value?: string): string | null {
  const cleaned = value?.replace(/\s+/g, " ").trim().slice(0, 140) ?? "";
  return cleaned.length > 0 ? cleaned : null;
}

/** Rebuild the app deep link from sanitized values only. */
function buildDeepLink(params: {
  to: string;
  amount: string | null;
  token: string;
  networkId: string;
  note: string | null;
}): string {
  let link = `bearo://pay?to=${encodeURIComponent(params.to)}`;
  if (params.amount) link += `&amount=${encodeURIComponent(params.amount)}`;
  link += `&token=${encodeURIComponent(params.token)}`;
  link += `&network=${encodeURIComponent(params.networkId)}`;
  if (params.note) link += `&note=${encodeURIComponent(params.note)}`;
  return link;
}

// -- Metadata -----------------------------------------------------------------

export async function generateMetadata({
  searchParams,
}: PayPageProps): Promise<Metadata> {
  const params = await searchParams;
  const to = sanitizeUsername(params.to);
  const amount = sanitizeAmount(params.amount);
  const token = sanitizeToken(params.token);

  const title = to ? `Pay @${to} on Bearo` : "Pay with Bearo";
  const description = to
    ? amount
      ? `@${to} is requesting $${amount} ${token} on Bearo — instant, gasless crypto payments.`
      : `@${to} is requesting a payment on Bearo — instant, gasless crypto payments.`
    : "Instant, gasless crypto payments. Send money to anyone, anywhere.";

  return buildBearoSocialMetadata({
    title,
    description,
    path: "/pay",
    surface: "pay",
    imageAlt: to
      ? `Bearo payment request from @${to}.`
      : "Bearo payment request.",
    imageParams: {
      to: to ?? undefined,
      amount: amount ?? undefined,
      token,
    },
  });
}

// -- Page ---------------------------------------------------------------------

export default async function PayPage({ searchParams }: PayPageProps) {
  const params = await searchParams;
  const to = sanitizeUsername(params.to);
  const amount = sanitizeAmount(params.amount);
  const token = sanitizeToken(params.token);
  const network = sanitizeNetwork(params.network);
  const note = sanitizeNote(params.note);

  const deepLink = to
    ? buildDeepLink({ to, amount, token, networkId: network.id, note })
    : null;

  return (
    <main className="min-h-screen bg-[#0a0a0b] text-white flex flex-col">
      {/* Header */}
      <header className="w-full px-6 pt-8 pb-4">
        <Link href="/" className="inline-block">
          <img
            src="/images/BearoApp.png"
            alt="Bearo"
            className="w-16 h-16 rounded-2xl"
          />
        </Link>
      </header>

      {/* Main Content */}
      <div className="flex-1 flex flex-col items-center justify-center px-6 pb-12 -mt-8">
        {/* Bear Logo */}
        <div className="mb-8">
          <img
            src="/images/BearoApp.png"
            alt="Bearo"
            className="w-28 h-28 rounded-3xl shadow-lg shadow-orange-500/20"
          />
        </div>

        {/* Request headline */}
        {to ? (
          <>
            <h1 className="text-3xl sm:text-4xl font-bold text-center mb-3">
              <span className="text-[#f97316]">@{to}</span> requests{" "}
              {amount ? `$${amount}` : "a payment"}
            </h1>
            <p className="text-gray-400 text-center text-lg mb-2 max-w-md">
              {token} on {network.name} — instant and gasless with Bearo.
            </p>
          </>
        ) : (
          <>
            <h1 className="text-3xl sm:text-4xl font-bold text-center mb-3">
              Pay with <span className="text-[#f97316]">Bearo</span>
            </h1>
            <p className="text-gray-400 text-center text-lg mb-2 max-w-md">
              Instant crypto payments. Send money to anyone, anywhere.
            </p>
          </>
        )}

        {/* Payment note */}
        {note && (
          <div className="mt-4 mb-2 px-5 py-3 rounded-2xl bg-white/5 border border-white/10 max-w-md">
            <p className="text-sm text-gray-400 text-center">Note</p>
            <p className="text-lg italic text-white text-center break-words">
              &ldquo;{note}&rdquo;
            </p>
          </div>
        )}

        {/* CTA Buttons */}
        <div className="w-full max-w-sm space-y-3 mt-8">
          {deepLink && (
            <a
              href={deepLink}
              className="block w-full text-center py-4 px-6 rounded-2xl font-semibold text-lg text-white bg-white/10 border border-white/15 transition-transform active:scale-[0.98]"
            >
              Open in Bearo
            </a>
          )}

          <a
            href={IOS_TESTFLIGHT_URL}
            className="block w-full text-center py-4 px-6 rounded-2xl font-semibold text-lg rainbow-border text-white transition-transform active:scale-[0.98]"
            style={{
              background: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
            }}
          >
            Download Bearo
          </a>

          <div className="block w-full text-center py-4 px-6 rounded-2xl font-medium text-gray-500 bg-white/5 border border-white/10 cursor-default">
            {ANDROID_WAITLIST_LABEL}
          </div>
        </div>

        {/* How It Works */}
        <div className="mt-12 w-full max-w-sm">
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4 text-center">
            How It Works
          </h2>
          <div className="space-y-4">
            <div className="flex items-start gap-4">
              <div className="w-8 h-8 rounded-full bg-[#f97316]/20 flex items-center justify-center shrink-0 mt-0.5">
                <span className="text-[#f97316] font-bold text-sm">1</span>
              </div>
              <div>
                <p className="text-white font-medium">Download Bearo</p>
                <p className="text-gray-500 text-sm">
                  Get the app from the App Store or TestFlight
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="w-8 h-8 rounded-full bg-[#f97316]/20 flex items-center justify-center shrink-0 mt-0.5">
                <span className="text-[#f97316] font-bold text-sm">2</span>
              </div>
              <div>
                <p className="text-white font-medium">
                  {to ? (
                    <>
                      Find <span className="text-[#f97316]">@{to}</span> in the app
                    </>
                  ) : (
                    "Create your account in seconds"
                  )}
                </p>
                <p className="text-gray-500 text-sm">
                  {to
                    ? "Search the username and confirm the amount"
                    : "Sign up with just your email — no seed phrases"}
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="w-8 h-8 rounded-full bg-[#f97316]/20 flex items-center justify-center shrink-0 mt-0.5">
                <span className="text-[#f97316] font-bold text-sm">3</span>
              </div>
              <div>
                <p className="text-white font-medium">Send the payment</p>
                <p className="text-gray-500 text-sm">
                  Instant settlement with zero gas fees
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="w-full px-6 py-6 text-center">
        <p className="text-gray-600 text-xs">
          BearifiedCo LLC. Crypto payments made simple.
        </p>
        <div className="flex justify-center gap-4 mt-2">
          <Link
            href="/privacy"
            className="text-gray-600 text-xs hover:text-gray-400 transition-colors"
          >
            Privacy
          </Link>
          <Link
            href="/terms"
            className="text-gray-600 text-xs hover:text-gray-400 transition-colors"
          >
            Terms
          </Link>
        </div>
      </footer>

      {/* Client component attempts to open the app via deep link */}
      {deepLink && <PayClient deepLink={deepLink} />}
    </main>
  );
}
